from __future__ import annotations

from pathlib import Path
import subprocess
from typing import Iterable


def generate_vivado_tcl(
    root: Path,
    rtl_files: Iterable[Path],
    xdc_files: Iterable[Path],
    out_dir: Path,
    top: str | None = None,
    part: str = "xc7k325tffg900-2",
) -> str:
    lines: list[str] = []
    lines.append("# Auto-generated by fpga-debug-agent")
    lines.append("set_param general.maxThreads 8")
    lines.append(f"set output_dir {{{out_dir.as_posix()}}}")
    lines.append("file mkdir $output_dir")
    lines.append(f"set_part {part}")
    for rtl in rtl_files:
        rel = rtl.resolve().as_posix()
        if rtl.suffix.lower() in {".sv", ".svh"}:
            lines.append(f"read_verilog -sv {{{rel}}}")
        else:
            lines.append(f"read_verilog {{{rel}}}")
    for xdc in xdc_files:
        lines.append(f"read_xdc {{{xdc.resolve().as_posix()}}}")
    if top:
        lines.append(f"synth_design -top {top} -part {part}")
    else:
        lines.append("# TODO: add synth_design -top <top_module> -part <part>")
    lines.extend(
        [
            "report_timing_summary -file $output_dir/timing_summary_post_synth.rpt",
            "report_timing -max_paths 20 -delay_type max -sort_by slack -file $output_dir/setup_paths.rpt",
            "report_timing -max_paths 20 -delay_type min -sort_by slack -file $output_dir/hold_paths.rpt",
            "report_cdc -details -file $output_dir/cdc_report.rpt",
            "# Uncomment for implementation stage:",
            "# opt_design",
            "# place_design",
            "# route_design",
            "# report_timing_summary -file $output_dir/timing_summary_post_route.rpt",
            "exit",
        ]
    )
    return "\n".join(lines) + "\n"


def run_vivado(vivado_bin: str, tcl_path: Path, cwd: Path) -> subprocess.CompletedProcess[str]:
    return subprocess.run(
        [vivado_bin, "-mode", "batch", "-source", str(tcl_path)],
        cwd=str(cwd),
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
        check=False,
    )
